Allow to specify any host (not just github.com and githubenterprise.com)
jcansdale/gpr pull request #116
Opened 2022-08-01 12:58 UTC by kegesch

Github Enterprise instances can have any domain.

2022-08-03 05:56 UTC, N3rv0us commented on src/GprTool/NuGetUtilities.cs
> +            if (!Uri.TryCreate(repositoryUrl, UriKind.Absolute, out var repositoryUri))
You can also remove the private method `IsSupportedHost` and the definition of supported hosts `m_supportedHosts`

2022-08-03 15:08 UTC, jcansdale requested changes
Thanks for the PR!

Could you add some new test cases covering non-Gitub URLs here?
https://github.com/kegesch/gpr/blob/e1d27f1edee84439a029659f0057fcacf4ee4421/test/GprTool.Tests/NuGetUtilitiesTests.cs#L192

2022-08-04 09:44 UTC, Qubitza approved these changes

2022-08-04 09:45 UTC, kegesch commented
@jcansdale I fixed the test case for `BuildOwnerAndRepositoryFromUrl` and added one where you suggested.
@Qubitza I removed the unused methods.

2022-08-04 14:18 UTC, jcansdale commented
@kegesch it looks like I'll need to use my admin privileges to merge. Shall I go ahead and merge?

2022-08-04 14:30 UTC, kegesch commented
@jcansdale you're right. Please go ahead.

2022-08-04 14:45 UTC, merged

2022-08-04 14:55 UTC, jcansdale commented
@kegesch the new version has been published to DockerHub and nuget.org (it should appear in a few minutes)!
https://github.com/jcansdale/gpr/runs/7674852752?check_suite_focus=true#step:3:14

Thanks for your contribution! 😄

2022-08-04 19:49 UTC, kegesch commented
Perfect! Thanks for the fast release 👍🏻